# Generated by Django 3.0.8 on 2020-07-31 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destinations',
            name='image',
            field=models.ImageField(upload_to='pics/'),
        ),
    ]
